### ISSUE TITLE
Tests are failing since upgrade of graphql-core from 2.3.1 to 2.3.2

### ISSUE THREAD

**Issue by leszekhanusz** [graphql-python/gql#80]
$ pytest tests

...

ERROR tests/starwars/test_dsl.py - TypeError: __init__() got an unexpected keyword argument 'type'
ERROR tests/starwars/test_query.py - TypeError: __init__() got an unexpected keyword argument 'type'
ERROR tests/starwars/test_validation.py - TypeError: __init__() got an unexpected keyword argument 'type'

**Comment by leszekhanusz** [comment]
My bad ... I did not notice the changes on the master branch...

Sorry for the noise

**Comment by Cito** [comment]
Fixed that just now after you reported it. Travis is still failing, but it looks like this is due to GitHub issues (rate limiter or something - need to retry later).
